name: Build

on: [push, pull_request]

jobs:
  ios:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    # - name: Prepare Root Directory
    #   env:
    #       DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
    #   run: |
    #     pod install

    - name: Submodules
      run: |
        git submodule update --init --recursive

    - name: Prepare Build Dependencies
      working-directory: ./TesseractOCR
      run: |
        brew install make cmake curl libtool pkg-config autoconf automake m4 ruby-build gnutls gnu-getopt

    - name: Prepare Build Directory
      working-directory: ./TesseractOCR
      run: |
        ./tesseract-ocr-patch.sh

    - name: Cross Compile Libraries
      working-directory: ./TesseractOCR
      env:
          DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
      run: |
        make -d

    - name: TEST Debug Build
      working-directory: ./TesseractOCR
      run: |
        xcodebuild -workspace Tesseract-OCR-iOS.xcworkspace -scheme TesseractOCR -configuration Debug -sdk iphonesimulator

    - name: TEST Release Build
      working-directory: ./TesseractOCR
      run: |
        xcodebuild -workspace Tesseract-OCR-iOS.xcworkspace -scheme TesseractOCR -configuration Release -sdk iphonesimulator
